- name: Install PostgreSQL dependencies
  action: apt pkg={{item}} state=latest
  with_items:
    - postgresql-client-{{ postgresql_version }}
    - postgresql-contrib-{{ postgresql_version }}
    - libpq-dev

- name: Add PostgreSQL repo key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc

- name: Add PostgreSQL repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'

- name: Install PostgreSQL
  apt: pkg=postgresql-{{ postgresql_version }} update_cache=true

- name: Copy valid pg_hba.conf
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf

- name: Copy valid postgresql.conf
  template: src=postgresql.conf.j2 dest=/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf

- name: Restart PostgreSQL
  service: name=postgresql state=restarted

- name: Create the postgresql database for application
  postgresql_db: name={{ postgresql_db_name }}
  sudo: yes
  sudo_user: postgres

- name: ensure user has access to database
  postgresql_user: db={{ postgresql_db_name }} name={{ postgresql_db_user }} password={{ postgresql_db_password }} priv=ALL
  sudo: yes
  sudo_user: postgres


