- name: Install PostgreSQL dependencies
  action: apt pkg={{item}} state=latest
  with_items:
    - python-pycurl
    - python-psycopg2
    - postgresql-contrib
    - libpq-dev

- name: Add PostgreSQL repo key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc

- name: Add PostgreSQL repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main'

- name: Install PostgreSQL
  apt: pkg=postgresql-{{ postgresql_version }} state=latest update_cache=true

- name: Copy valid pg_hba.conf
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf

- name: Copy valid postgresql.conf
  template: src=postgresql.conf.j2 dest=/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf

- name: Restart PostgreSQL
  command: service postgresql restart

- name: Create the postgresql user for application
  postgresql_user: '{{ postgresql_db_user }}' 
  sudo: yes
  sudo_user: postgres

- name: Create the postgresql database for application
  postgresql_db: name=app_{{ app_name }} owner={{ postgresql_db_user }} state=present
  sudo: yes
  sudo_user: postgres
